Attribute VB_Name = "M22_CALLS"
Sub RELATORIO_DIARIO_A_FATURAR()

Call M01_BASE_V6.M1_BASE_V3
Call M02_CONV_PERFIS.Menu
Call M03_MOLDURAS.molduras
Call M03_MOLDURAS.Molduras_2
Call M07_ACESSÓRIOS.Menu
Call M08_PEDIDOS_ABERTO.Menu


End Sub

Sub RELATORIO_DIARIO_VENDAS()

Call M01_BASE_V6.M1_BASE_V3
Call M21_VENDAS_MOLDURAS.MOLDURAS_VENDAS
Call M10_FAT_SEMANAL.Menu

End Sub

Sub RELATORIO_DIARIO_FATURADO()

Call M01_BASE_V6.M1_BASE_V3
Call M21_VENDAS_MOLDURAS.MOLDURAS_VENDAS
Call M10_FAT_SEMANAL.Menu
Call M03_MOLDURAS.molduras

End Sub

Sub RELATORIO_MENSAL()

'Call M01_BASE_V6.M1_BASE_V3
Call M05_IVONE.Executar_Ivone
Call M06_GIOVANI.Menu
Call M10_FAT_SEMANAL.Menu
Call M03_MOLDURAS.molduras
Call M21_VENDAS_MOLDURAS.MOLDURAS_VENDAS

End Sub

